### ISSUE TITLE
TypeError: client.write is not a function

### ISSUE THREAD

**Issue by zxfrank** [markwylde/liferaft#3]
Hello internet,
I may have done something wrong... I'm starting to play with this module and I can't manage to make it work.

TypeError: client.write is not a function
    at wrapper (node_modules/@markwylde/liferaft/index.js:600:14)
    at Raft.message (node_modules/@markwylde/liferaft/index.js:639:7)
    at Raft.promote (node_modules/@markwylde/liferaft/index.js:717:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) @NotifyFeature.onUnhandledRejection 

If I log `client` where's the error, I get
```
<ref *1> Raft {
  _events: Events <[Object: null prototype] {}> {
    'term change': EE { fn: [Function: change], context: [Circular *1], once: false },
    'state change': EE { fn: [Function: change], context: [Circular *1], once: false },
    data: EE {
      fn: [AsyncFunction (anonymous)],
      context: [Circular *1],
      once: false
    },
    end: EE { fn: [Function: end], context: [Raft], once: true }
  },
  _eventsCount: 4,
  election: { min: 150, max: 300 },
  beat: 50,
  votes: { for: null, granted: 0 },
  write: null,
  threshold: 0.8,
  address: 'tcp://IP_ADDRESS:PORT',
  timers: Tick { timers: {}, context: [Circular *1] },
  Log: undefined,
  change: [Function: change],
  emits: [Function: emits],
  latency: 0,
  log: null,
  nodes: [],
  state: 4,
  leader: '',
  term: 0
}
```

ubuntu 20.04
node v16.15.0
npm v8.10.0

what am I doing wrong?
thanks

**Comment by markwylde** [comment]
I've just tried cloning it fresh and it all worked fine for me, although I'm on ubuntu 22.

ubuntu 22
node v16.14.2
npm 8.5.0

What code are you trying to run? Does the [example](https://github.com/markwylde/liferaft/tree/master/example) work for you?

**Comment by zxfrank** [comment]
the example is working, I npm installed it into my project. I copied the "extends" with the init and write functions and it works.

I can't say it's stable but it works. thanks
